# Generated by Django 3.2.16 on 2022-12-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20221222_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='statue',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
