# Generated by Django 3.2.16 on 2023-01-06 15:10

from django.db import migrations
import galleryfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_statue_skip'),
    ]

    operations = [
        migrations.AddField(
            model_name='statue',
            name='gallery',
            field=galleryfield.fields.GalleryField(default='exit', target_model='galleryfield.BuiltInGalleryImage'),
            preserve_default=False,
        ),
    ]
