# Generated by Django 3.2.16 on 2023-01-06 15:10

from django.db import migrations
import galleryfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_statue_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statue',
            name='gallery',
            field=galleryfield.fields.GalleryField(blank=True, null=True, target_model='galleryfield.BuiltInGalleryImage'),
        ),
    ]
