# Generated by Django 3.2.16 on 2023-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_statue_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='statue',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
