# Generated by Django 3.2.16 on 2023-02-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_statue_happy_horse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='statue',
            name='main_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('score', models.SmallIntegerField(default=0, help_text="-1 for dislike, 1 for like, 0 for don't know")),
                ('statue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.statue')),
            ],
        ),
    ]
