# Generated by Django 4.1.6 on 2023-02-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_statue_happy_horse_statue_missing_image_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='servant_partner',
            field=models.IntegerField(default=99),
        ),
    ]
