# Generated by Django 4.1.6 on 2023-03-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_statue_scored_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='statue',
            name='like_dontknow',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statue',
            name='like_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statue',
            name='like_yes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
