# Generated by Django 4.1.6 on 2023-03-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_statue_servant_partner_avg'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseColor',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('coat_color_css', models.CharField(default='black', max_length=7)),
                ('mane_color_css', models.CharField(default='black', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
