# Generated by Django 4.2.16 on 2024-11-21 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0019_horsecolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislike',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='source',
            field=models.CharField(default='Equistatue', max_length=12),
        ),
        migrations.AddField(
            model_name='statue',
            name='public_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
