# Generated by Django 4.2.16 on 2024-11-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_likedislike_session_id_likedislike_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statue',
            name='ref',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
