# Generated by Django 4.2.16 on 2024-11-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_remove_likedislike_session_id_remove_statue_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statue',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='statue_display_images/'),
        ),
    ]
